name: rivertion
description: Extends riverpod by adding the ability to manipulate data via asynchronous mutations / actions.
version: 0.1.0-dev.3
homepage: https://github.com/BreX900/query/riverpod_mutation

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # Blocked on flutter 3.0.x
  meta: ^1.7.0

  mek_data_class: ^0.1.0

  rxdart: ^0.27.4

  bloc: ^8.0.3
  riverpod: ^2.0.0-dev.9
  riverbloc: ^2.0.0-dev.3

dev_dependencies:
  # dart run build_runner build --delete-conflicting-outputs
  # dart run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.11
  mek_data_class_generator: ^0.1.3

  test: ^1.21.3
  mocktail: ^0.3.0

  mek_lints: ^0.2.0